### ISSUE TITLE
ne_result_get should be looked at

### ISSUE THREAD

**Issue by playmer** [TrevorSundberg/ne#3]
I've been briefly reviewing the header and I noticed the ne_result_get function call. It seems like folks consider this sort of pattern for error handling to be a mistake, primarily for threading reasons. I'll direct to  Arthur's post on the SG14 Google group here:

https://groups.google.com/a/isocpp.org/forum/#!msg/sg14/fBLwNO8Wu48/Hl-odOZ_AgAJ

They point out that as new primitives for dealing with concurrency are introduced, we'll continue to run into issues with our error primitive. This is in context of Niall proposing a new error type (for C in this case, despite SG14 being a C++ study group), so that more languages (C++/Rust/Swift/Others) can intercommunicate their exceptional/error states.

Just something to consider.

**Comment by TrevorSundberg** [comment]
I'm convinced. I'm going to take an error enum or structure as either the first or last parameter of every function. I'm expecting this to be a pointer, where null is always an option if you wish to ignore the error.

Part of the reason I chose the thread local result was that there are many functions that when implemented reasonably on any platform will never fail. For example, I can't think of any reason `ne_timer_count` would ever fail. That said, I wanted to be future compatible and not write myself into a corner by not taking an error parameter (in case for some reason on a future platform it actually *can* fail). Hence I chose a global thread local because it always gives the API that option. But as I said, I'm convinced just because of fibers. Thanks for that!
